### ISSUE TITLE
Issue with counsel-etags-scan-dir

### ISSUE THREAD

**Issue by Chiasung** [nilsdeppe/MyEnvironment#3]
Recently I build my environment. And I got the following error. 
Can you give me the guidance to fix this > .  Thank you in advance!

` counsel-etags-scan-dir:`` Wrong number of arguments: (lambda nil (interactive) (let* ((tags-file (counsel-etags-locate-tags-file))) (if tags-file (progn (my-scan-dir (file-name-directory tags-file) t) (run-hook-with-args (quote counsel-etags-after-update-tags-hook) tags-file) (if counsel-etags-quiet-when-updating-tags nil (message "%s is updated!" tags-file)))))), 1

**Comment by nilsdeppe** [comment]
Hey, I just updated the configuration completely. Could you try rebuild with the latest and let me know which emacs version you're using? I'm using 26.3

**Comment by Chiasung** [comment]
I am sorry for the late to response this. Previously I used version 25.3 and I realize the gpg key was changed. After I switch to 26.3. The problem is solved.
